CREATE TABLE `artifacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `branch` varchar(100) NOT NULL,
  `museum` varchar(100) NOT NULL,
  `artifact_type` varchar(100) NOT NULL,
  `piece_number` varchar(50) NOT NULL,
  `record_number` varchar(50) DEFAULT NULL,
  `discovery_place` varchar(100) DEFAULT NULL,
  `source` varchar(50) DEFAULT NULL,
  `acquisition_date` date DEFAULT NULL,
  `material` varchar(100) DEFAULT NULL,
  `color` varchar(50) DEFAULT NULL,
  `time_period` varchar(100) DEFAULT NULL,
  `height` decimal(10,2) DEFAULT NULL,
  `width` decimal(10,2) DEFAULT NULL,
  `length` decimal(10,2) DEFAULT NULL,
  `diameter` decimal(10,2) DEFAULT NULL,
  `depth` decimal(10,2) DEFAULT NULL,
  `weight` decimal(10,2) DEFAULT NULL,
  `condition` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `published_by` text DEFAULT NULL,
  `documenter` varchar(100) NOT NULL,
  `documentation_date` date NOT NULL,
  `image_path` varchar(255) DEFAULT NULL,
  `catalog_number` varchar(50) DEFAULT NULL,
  `card_number` varchar(50) DEFAULT NULL,
  `guide_number` varchar(50) DEFAULT NULL,
  `previous_number` varchar(50) DEFAULT NULL,
  `storage_location` varchar(100) DEFAULT NULL,
  `room` varchar(50) DEFAULT NULL,
  `safe` varchar(50) DEFAULT NULL,
  `storage` varchar(50) DEFAULT NULL,
  `shelf` varchar(50) DEFAULT NULL,
  `previous_location` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `piece_number` (`piece_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;